### ISSUE TITLE
DPO training on 4 A10s

### ISSUE THREAD

**Issue by Aakriti05** [RifleZhang/LLaVA-Hound-DPO#8]
I am running the DPO training code on 4 A10s (total memory = 96G) but I am getting memory error. 

```
Traceback (most recent call last):                                                                                                                                         
  File "/dlbimg/LLaVA-Hound-DPO/llava_hound_dpo/dpo_scripts/run_dpo.py", line 897, in <module>                                                                             
    train(attn_implementation="flash_attention_2")                                                                                                                         
  File "/dlbimg/LLaVA-Hound-DPO/llava_hound_dpo/dpo_scripts/run_dpo.py", line 875, in train                                                                                
    trainer.train()                                                                                                                                                        
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train                                                       
    return inner_training_loop(                                                                                                                                            
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/transformers/trainer.py", line 1672, in _inner_training_loop                                        
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)                                                                                           
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/accelerate/accelerator.py", line 1280, in prepare                                                   
    result = self._prepare_deepspeed(*args)                                                                                                                                
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/accelerate/accelerator.py", line 1662, in _prepare_deepspeed                                        
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)                                                                                                    
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize                                                     
    engine = DeepSpeedEngine(args=args,                                                                                                                                    
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 262, in __init__                                                 
    self._configure_distributed_model(model)                                                                                                                               
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1081, in _configure_distributed_model                            
    self.module.to(self.device)                                                                                                                                            
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2460, in to                                                   
    return super().to(*args, **kwargs)                                                                                                                                     
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to                                                       
    return self._apply(convert)                                                                                                                                            
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply                                                    
    module._apply(fn)                                                                                                                                                      
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply                                                    
    module._apply(fn)                                                                                                                                                      
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply                                                    
    module._apply(fn)                                                                                                                                                      
  [Previous line repeated 2 more times]                                                                                                                                    
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply                                                    
    param_applied = fn(param)                                                                                                                                              
  File "/home/aagra/anaconda3/envs/vllava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert                                                  
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)                                                                          
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 2 has a total capacty of 21.99 GiB of which 5.38 MiB is free. Including non-PyTorch memor
y, this process has 21.97 GiB memory in use. Of the allocated memory 21.60 GiB is allocated by PyTorch, and 17.40 MiB is reserved by PyTorch but unallocated. If reserved b
ut unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF     
```

I reduced the batch-size and adjusted the  following parameter, but still got exactly same (32Mib) memory error. Do you have any suggestions on what I can do to run on 4 A10s ?

```
--per_device_train_batch_size 1 \
 --per_device_eval_batch_size 4 \
 --gradient_accumulation_steps 2 \
```

**Comment by RifleZhang** [comment]
I think total of 96G may not fit the full model training. 

Maybe you can try with LoRA training. I didn't test LoRA, but the LLaVA code should support LoRA training. You can check how to run from the llava official codebase.

My suggestion is to try SFT first, as DPO needs additional copy of model on the device. 

Also, for debugging purpose, you can try to uncomment https://github.com/RifleZhang/LLaVA-Hound-DPO/blob/main/llava_hound_dpo/llava/model/llava_arch.py#L168

Video-llava architecture needs 2048 tokens for each video, this can use the first 256 tokens, just to check how much of a model can fit on your devices.

**Comment by Aakriti05** [comment]
hi lora solved the problem.
